### ISSUE TITLE
The point cloud scanning software used by Intel RealSense SR300 scanner

### ISSUE THREAD

**Issue by bearprin** [galmetzer/self-sample#3]
Hi, thanks for your impressive work!

Your results, especially under real scans scanned by SR300, are very robust for different point cloud artifacts. 

So I want to experiment self-sample with more real scans scanned by my own SR300, but I only scanned depth maps before based on SDK thus I am not very familiar with point cloud scanning.

My question is which software are used by Intel RealSense SR300 scanner to scan the point cloud? The software in the official SDK is not very convenient for object scanning. Besides, I have found `itSeez3D`, but it seems can only produce mesh but not point cloud.

Looking forward to your reply.

**Comment by galmetzer** [comment]
Hi, so the point clouds from the SR300 sensor were obtained thanks to [Guy](https://github.com/guyoffe), a good friend of mine. 
He published the code for his project that used the SR300, which can be found [here](https://github.com/Haifa3D/hand-scan), together with a thorough README explaining how to use the program.
He also kindly pointed me to this [script](https://github.com/Haifa3D/hand-scan/blob/master/code/python/calibrate_and_capture.py) that should be a good reference for getting point clouds using python.
I hope that answers your question :)

**Comment by bearprin** [comment]
Awesome！ I will follow its instructions and try to scan shapes by myself. Thank you very much!
